### ISSUE TITLE
some incorrect word boundaries

### ISSUE THREAD

**Issue by dkawahara** [FairyDevicesRD/FairyMaCorpus#1]
The following word boundaries in adj.tsv seem to be incorrect:

歌声は|ハスキー|で太く、オペラの歌唱法に強い影響を受けたビブラートが持ち味。	形容詞-*	ハスキーで
-> |ハスキーで|

高性能で|レア|なものほど高額のＲＰを必要とするが、パーツごとに決められた額のＲＰを支払いさえすれば、敵から奪えないものはない。	形容詞-*	レアな
-> |レアな|

トラス橋としての中央径間５１０ｍは|日本?最長|で、世界第３位の長さである。	形容詞-*	最長で
-> |日本?最長で|

**Comment by dkawahara** [comment]
The following word boundary in verb.tsv is also incorrect:

水軍は|陳?璘率|いる明水軍１９，４００人、朝鮮水軍７，３２８人は李舜臣が率いた。	動詞-*	率いる
-> |陳?璘|

**Comment by shirayu** [comment]
Thank you for your comments!
